servos = {
    "LEFT_SHOULDER_INOUT":       100,
    "LEFT_SHOULDER_FOREAFT":     101,
    "LEFT_UPPERARM_ROTATE":      102,
    "LEFT_ELBOW":                103,
    "LEFT_WRIST_ROTATE":         104,
    "LEFT_WRIST_LEFTRIGHT":      105,
    "LEFT_WRIST_UPDOWN":         106,
    "LEFT_HAND":                 107,
    "RIGHT_SHOULDER_INOUT":      108,
    "RIGHT_SHOULDER_FOREAFT":    109,
    "RIGHT_UPPERARM_ROTATE":     110,
    "RIGHT_ELBOW":               111,
    "RIGHT_WRIST_ROTATE":        112,
    "RIGHT_WRIST_LEFTRIGHT":     113,
    "RIGHT_WRIST_UPDOWN":        114,
    "RIGHT_HAND":                115,
    "NECK_PAN":                  116,
    "NECK_TILT":                 117,
    "NECK_ROLL":                 118,
}